### ISSUE TITLE
Content of: docker-compose-executor.sh

### ISSUE THREAD

**Issue by kurtkopchik** [mohitsoni/compose-executor#2]
Do you have a sample of what the content of the executor script is supposed to be?
"executor":"/code/docker-compose-executor.sh"

**Comment by ridv** [comment]
This is an example, but I think we're trying to move away from using .sh, we only used it to get stuff working at the hackathon.

https://github.com/rdelval/aurora/blob/compose-demo/docker_comp_executor.sh

**Comment by kurtkopchik** [comment]
Got it. BTW - This is a great project! Exactly what I was looking to do.
