### ISSUE TITLE
volume_from rewrite support

### ISSUE THREAD

**Issue by kurtkopchik** [mohitsoni/compose-executor#5]
I wanted to add support to also rewrite the compose 'volume_from' field in DockerRewriteHelper but it does not look like I have permission to create a pull request. Here is the code that would add this functionality.

```
private static final String VOLUMES_FROM = "volumes_from";

Object volumesFromValues = containerDetails.get(VOLUMES_FROM);
if(volumesFromValues != null){
    List<String> updatedVolumesFrom = new ArrayList<String>();
    @SuppressWarnings("unchecked")
    List<String> volumesFrom = (ArrayList<String>)volumesFromValues;
    for(String volumeFrom:volumesFrom){
        updatedVolumesFrom.add(prefixTaskId(taskId, volumeFrom));
    }
    containerDetails.put(VOLUMES_FROM, updatedVolumesFrom);
}
```

**Comment by mohitsoni** [comment]
@kurtkopchik Thanks for the patch. I am curious why you are not able to send the pull request.
I just checked the repo settings and there's no setting that stops someone from sending the pull request.
I also looked at your fork: https://github.com/kurtkopchik/compose-executor and I didn't see the above patch committed into your fork, which makes me wonder if by mistake you are trying to push the patch to this repository? It happens with me all the time.
Can you please check what your remote is configured to with: git remote -v

Please make sure your local git is pointing to https://github.com/kurtkopchik/compose-executor, that will ensure that you can commit and push changes to https://github.com/kurtkopchik/compose-executor

Once you have done that you can easily send the pull request.

**Comment by kurtkopchik** [comment]
Thanks @mohitsoni you are correct. I had not pointed to my fork. I've submitted the pull request.

**Comment by gtejasvarma** [comment]
merged pull request. Thanks @kurtkopchik
