### ISSUE TITLE
Docker Compose Pull before Launch Task

### ISSUE THREAD

**Issue by kurtkopchik** [mohitsoni/compose-executor#6]
In order to get the most up to date image when running in Mesos the compose-executor should really perform a "docker-compose -f <filename> pull" prior to the Launch Task. Otherwise, docker-compose is going to start up with whatever happens to be on the slave node instead of first grabbing the "latest" version that's available.

**Comment by gtejasvarma** [comment]
@kurtkopchik will add this. Thanks for pointing out.

**Comment by mbdas** [comment]
Agree. Can you send a pull request? As Mohit replied in last issue, you should be fine submitting them.
One other thing in most use cases avoid using the "latest" tag and have explicit versioned tag for your new app build. "latest" in docker may not point to latest tag and can cause confusion.

**Comment by gtejasvarma** [comment]
@kurtkopchik as @mbdas  pointed out it makes sense to pass label info as part of task definition. If it is not passed we don't pull anything. Do you see any issues with this ?

**Comment by kurtkopchik** [comment]
Are you saying that you will only pull if the Marathon payload includes a defined label? If so, I don't see any issue with that implementation.

**Comment by mbdas** [comment]
No it makes sense to add "docker-compose -f pull" for use cases where folks are not using explicit tagging and just relying on latest. Unfortunately there is no flag in docker-compose up to also force pull the image. So, we will do an explicit pull.

I was mentioning the fact if one uses images like   xx/yy:version where version bits change on each docker build for the tag, then a container launch will pull the new image as there is no cache that can serve it but if one relies on xx/yy:latest then one can hit the stale issue.

Nothing to do with labels.

**Comment by kurtkopchik** [comment]
Thanks @mbdas that explanation aligns what my understanding as well. The explicit pull will ensure that the stale xx/yy:latest case is covered. Looking forward to having this fixed in the official branch.

**Comment by gtejasvarma** [comment]
Done.
commit id# https://github.com/mohitsoni/compose-executor/commit/150e925265d00263b9e2f8a870555dec0bed6bae
